base_url = "https://esatakpunar.github.io/est"
title = "est"
compile_sass = false
build_search_index = false

[markdown]
highlighting = { theme = "one-dark-pro" }

[extra]
description = "est — Ultra-lightweight, zero dependency, semantic HTML/CSS/JS UI library"
